security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/user/login
            stateless: true
            security: false

        projects:
            pattern: ^/projects
            stateless: true
            provider: app_user_provider
            jwt: ~

        api:
            pattern: ^/user
            stateless: true
            provider: app_user_provider
            jwt: ~

        role:
            pattern: ^/role
            stateless: true
            provider: app_user_provider
            jwt: ~

        notes:
            pattern: ^/notes
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/admin/create, roles: ROLE_ADMIN }
        - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/role, roles: ROLE_ADMIN }
        - { path: ^/projects/new, roles: ROLE_ADMIN }
        - { path: ^/projects/[0-9]+/delete, roles: ROLE_ADMIN }
        - { path: ^/notes, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
