services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-wimmov_db} # Nom personnalisé de la base
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wimmov} # Mot de passe personnalisé
      POSTGRES_USER: ${POSTGRES_USER:-user} # Nom d'utilisateur personnalisé
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-wimmov_db}", "-U", "${POSTGRES_USER:-user}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432" # Port PostgreSQL (local:conteneur)
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8082:8080" # Port Adminer (local:conteneur)
    environment:
      ADMINER_DEFAULT_SERVER: database # Fait référence au service "database"
    depends_on:
      database:
        condition: service_healthy

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
